### ISSUE TITLE
GhostScript Checks never succeeds

### ISSUE THREAD

**Issue by LuemmelSec** [BC-SECURITY/Moriarty#7]
The Ghost Script check never succeeds if the tool errors in the catch block. It will then directly exit.
This happens on all machines I tested:

![image](https://github.com/BC-SECURITY/Moriarty/assets/58529760/82bbeff7-b7c0-442f-b2e2-dc64573248f8)

I tried to quickly fix it but to no success.
The files are never found this way, even if they exist.

**Comment by Cx01N** [comment]
I put together an admin and non-admin version of the check now. It seems to be working for me if you want to check it out too.
